config/routes.rb
EvokeTruegmRails::Application.routes.draw do

  resources :rosters
  resources :nfl_players, only: [:index]

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'rosters#index'

end

app/models/roster.rb
class Roster < ActiveRecord::Base
    validates :name, presence: true
    attr_accessible :name, :qb1, :rb1, :rb2, :wr1, :wr2, :te, :flex, :utility, :pk, :bench1, :bench2, :bench3, :bench4, :bench5, :bench6

    before_save :calculate_salary

    def calculate_salary
        player_ids = [self.qb1, self.rb1, self.rb2, 
                      self.wr1, self.wr2, self.te, 
                      self.flex, self.utility, self.pk,
                      self.bench1, self.bench2, self.bench3, 
                      self.bench4, self.bench5, self.bench6].flatten.uniq.compact
        self.salary = NflPlayer.where(id: player_ids).pluck(:salary).sum
    end
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
  before_action :set_roster, only: [:show, :edit, :update, :destroy]

  # GET /rosters
  # GET /rosters.json
  def index
    @rosters = Roster.all
  end

  # GET /rosters/1
  # GET /rosters/1.json
  def show
  end

  # GET /rosters/new
  def new
    @roster = Roster.new
  end

  # GET /rosters/1/edit
  def edit
  end

  # POST /rosters
  # POST /rosters.json
  def create
    @roster = Roster.new(roster_params)

      if @roster.save
        redirect_to @roster, notice: 'Roster was successfully created.'
      else
        render action: 'new'
      end
  end

  # PATCH/PUT /rosters/1
  # PATCH/PUT /rosters/1.json
  def update
      if @roster.update(roster_params)
        redirect_to @roster, notice: 'Roster was successfully updated.'
      else
        render action: 'edit'
      end
  end

  # DELETE /rosters/1
  # DELETE /rosters/1.json
  def destroy
    @roster.destroy
    redirect_to rosters_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roster
      @roster = Roster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roster_params
      params.require(:roster).permit(:name, :qb1, :rb1, :rb2, :wr1, :wr2, :te, :flex, :utility, :pk, :bench1, :bench2, :bench3, :bench4, :bench5, :bench6)
    end
end

app/helpers/rosters_helper.rb
module RostersHelper
end

app/views/rosters/_form.html.erb
<div class="row">
  <div class="col-sm-9">
<%= form_for(@roster) do |f| %>
  <% if @roster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roster.errors.count, "error") %> prohibited this roster from being saved:</h2>

      <ul>
      <% @roster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :qb1 %><br>
    <%= f.select :qb1, NflPlayer.positions("qb").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :rb1 %><br>
    <%= f.select :rb1, NflPlayer.positions("rb").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :rb2 %><br>
    <%= f.select :rb2, NflPlayer.positions("rb").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :wr1 %><br>
    <%= f.select :wr1, NflPlayer.positions("wr").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :wr2 %><br>
    <%= f.select :wr2, NflPlayer.positions("wr").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :te %><br>
    <%= f.select :te, NflPlayer.positions("te").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :flex %><br>
    <%= f.select :flex, NflPlayer.positions("flex").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :utility %><br>
    <%= f.select :utility, NflPlayer.positions("all").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :pk %><br>
    <%= f.select :pk, NflPlayer.positions("k").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <hr />
  <div class="field">
    <%= f.label :bench1 %><br>
    <%= f.select :bench1, NflPlayer.positions("all").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :bench2 %><br>
    <%= f.select :bench2, NflPlayer.positions("all").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :bench3 %><br>
    <%= f.select :bench3, NflPlayer.positions("all").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :bench4 %><br>
    <%= f.select :bench4, NflPlayer.positions("all").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :bench5 %><br>
    <%= f.select :bench5, NflPlayer.positions("all").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :bench6 %><br>
    <%= f.select :bench6, NflPlayer.positions("all").order(:full_name).map {|c| [c.full_name_with_salary, c.id, {:salary => c.salary}]}, :include_blank => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
    <div class="col-sm-3">
      <div class="field" data-spy="affix">
        <h3 id="js-total-salary">$0</h3>
        <h5>out of $32,000,000</h5>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/rosters/edit.html.erb
<h1>Editing Roster</h1>

<%= render 'form' %>

<%= link_to 'Show', @roster %> |
<%= link_to 'Back', rosters_path %>

app/views/rosters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rosters</h1>

<table class="table responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Total Salary</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @rosters.each do |roster| %>
      <tr>
        <td><%= roster.name %></td>
        <td><%= format_as_money roster.salary %></td>
        <td><%= link_to 'Show', roster %></td>
        <td><%= link_to 'Edit', edit_roster_path(roster) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roster', new_roster_path %>

app/views/rosters/new.html.erb
<h1>New Roster</h1>

<%= render 'form' %>

<%= link_to 'Back', rosters_path %>

app/views/rosters/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
<div class="row">
<p>
  <strong>Roster Name:</strong>
  <%= @roster.name %>
</p>

<p>
  <strong>Total Salary:</strong>
  <%= format_as_money @roster.salary %>
</p>

<p>
  <strong>Qb1:</strong>
  <%= NflPlayer.find(@roster.qb1).full_name_with_salary if @roster.qb1 %>
</p>

<p>
  <strong>Rb1:</strong>
  <%= NflPlayer.find(@roster.rb1).full_name_with_salary if @roster.rb1 %>
</p>

<p>
  <strong>Rb2:</strong>
  <%= NflPlayer.find(@roster.rb2).full_name_with_salary if @roster.rb2 %>
</p>

<p>
  <strong>Wr1:</strong>
  <%= NflPlayer.find(@roster.wr1).full_name_with_salary if @roster.wr1 %>
</p>

<p>
  <strong>Wr2:</strong>
  <%= NflPlayer.find(@roster.wr2).full_name_with_salary if @roster.wr2 %>
</p>

<p>
  <strong>Te:</strong>
  <%= NflPlayer.find(@roster.te).full_name_with_salary if @roster.te %>
</p>

<p>
  <strong>Flex:</strong>
  <%= NflPlayer.find(@roster.flex).full_name_with_salary if @roster.flex %>
</p>

<p>
  <strong>Utility:</strong>
  <%= NflPlayer.find(@roster.utility).full_name_with_salary if @roster.utility %>
</p>

<p>
  <strong>Pk:</strong>
  <%= NflPlayer.find(@roster.pk).full_name_with_salary if @roster.pk %>
</p>

<hr>

<p>
  <strong>Bench 1:</strong>
  <%= NflPlayer.find(@roster.bench1).full_name_with_salary if @roster.bench1 %>
</p>

<p>
  <strong>Bench 2:</strong>
  <%= NflPlayer.find(@roster.bench2).full_name_with_salary if @roster.bench2 %>
</p>

<p>
  <strong>Bench 3:</strong>
  <%= NflPlayer.find(@roster.bench3).full_name_with_salary if @roster.bench3 %>
</p>

<p>
  <strong>Bench 4:</strong>
  <%= NflPlayer.find(@roster.bench4).full_name_with_salary if @roster.bench4 %>
</p>

<p>
  <strong>Bench 5:</strong>
  <%= NflPlayer.find(@roster.bench5).full_name_with_salary if @roster.bench5 %>
</p>

<p>
  <strong>Bench 6:</strong>
  <%= NflPlayer.find(@roster.bench6).full_name_with_salary if @roster.bench6 %>
</p>
</div>
</div>
<%= link_to 'Edit', edit_roster_path(@roster) %> |
<%= link_to 'Back', rosters_path %>